[a-msedge.net] HTTPConnectionPool(host='a-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e364fd210>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[akamaiedge.net] HTTPConnectionPool(host='akamaiedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e32110590>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[akamai.net] HTTPConnectionPool(host='akamai.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3c22e310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[gtld-servers.net] HTTPConnectionPool(host='gtld-servers.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3b9d0850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[l-msedge.net] HTTPConnectionPool(host='l-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3bc6b790>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[domaincontrol.com] HTTPConnectionPool(host='domaincontrol.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3c120250>: Failed to establish a new connection: [Errno 111] Connection refused'))
[akadns.net] HTTPConnectionPool(host='akadns.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3c1222d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[windowsupdate.com] HTTPConnectionPool(host='windowsupdate.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e320f3010>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[nflxso.net] HTTPConnectionPool(host='nflxso.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3c5c0a90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[s-msedge.net] HTTPConnectionPool(host='s-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3c5c25d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[microsoftonline.com] HTTPConnectionPool(host='microsoftonline.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3b74a310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[netflix.net] HTTPConnectionPool(host='netflix.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9e3c0180d0>, 'Connection to netflix.net timed out. (connect timeout=None)'))
[trafficmanager.net] HTTPConnectionPool(host='trafficmanager.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3b916a10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[fdv2-t-msedge.net] HTTPConnectionPool(host='fdv2-t-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3b914550>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[cloudapp.net] HTTPConnectionPool(host='cloudapp.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3ba6ed90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[googleusercontent.com] HTTPConnectionPool(host='googleusercontent.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3ba6ca10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[apple-dns.net] HTTPConnectionPool(host='apple-dns.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3ba6c050>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[aaplimg.com] HTTPConnectionPool(host='aaplimg.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3c442dd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[edgekey.net] HTTPConnectionPool(host='edgekey.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3b5a4090>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[163.com] HTTPConnectionPool(host='163.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9e3c668fd0>, 'Connection to 163.com timed out. (connect timeout=None)'))
[macromedia.com] HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9e3b2b94d0>, 'Connection to macromedia.com timed out. (connect timeout=None)'))
[omtrdc.net] HTTPConnectionPool(host='omtrdc.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3bb101d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[msedge.net] HTTPConnectionPool(host='msedge.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9e3bb11dd0>, 'Connection to msedge.net timed out. (connect timeout=None)'))
[cloudfront.net] HTTPConnectionPool(host='cloudfront.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3bb111d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[ruidongcloud.com] HTTPConnectionPool(host='ruidongcloud.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3c135910>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[spo-msedge.net] HTTPConnectionPool(host='spo-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e3b3d5f90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
