[a-msedge.net] HTTPConnectionPool(host='a-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da11303d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[akamaiedge.net] HTTPConnectionPool(host='akamaiedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6677c10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[akamai.net] HTTPConnectionPool(host='akamai.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da5fd3790>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[gtld-servers.net] HTTPConnectionPool(host='gtld-servers.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6046cd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[l-msedge.net] HTTPConnectionPool(host='l-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6f235d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[domaincontrol.com] HTTPConnectionPool(host='domaincontrol.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da1226910>: Failed to establish a new connection: [Errno 111] Connection refused'))
[akadns.net] HTTPConnectionPool(host='akadns.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da116e810>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[windowsupdate.com] HTTPConnectionPool(host='windowsupdate.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da62f09d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[nflxso.net] HTTPConnectionPool(host='nflxso.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6430190>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[s-msedge.net] HTTPConnectionPool(host='s-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da689fb50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[microsoftonline.com] HTTPConnectionPool(host='microsoftonline.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da110d9d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[netflix.net] HTTPConnectionPool(host='netflix.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1da1117110>, 'Connection to netflix.net timed out. (connect timeout=None)'))
[trafficmanager.net] HTTPConnectionPool(host='trafficmanager.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da65b1890>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[fdv2-t-msedge.net] HTTPConnectionPool(host='fdv2-t-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da67b7f50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[cloudapp.net] HTTPConnectionPool(host='cloudapp.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da63cb050>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[googleusercontent.com] HTTPConnectionPool(host='googleusercontent.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6acc310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[apple-dns.net] HTTPConnectionPool(host='apple-dns.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6ae4f50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[edgekey.net] HTTPConnectionPool(host='edgekey.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6ae5510>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[aaplimg.com] HTTPConnectionPool(host='aaplimg.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da68f1110>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[163.com] HTTPConnectionPool(host='163.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1da5ffef90>, 'Connection to 163.com timed out. (connect timeout=None)'))
[macromedia.com] HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1da584d1d0>, 'Connection to macromedia.com timed out. (connect timeout=None)'))
[msedge.net] HTTPConnectionPool(host='msedge.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1da6567b50>, 'Connection to msedge.net timed out. (connect timeout=None)'))
[omtrdc.net] HTTPConnectionPool(host='omtrdc.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6ffa6d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[cloudfront.net] HTTPConnectionPool(host='cloudfront.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6ffa1d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[ruidongcloud.com] HTTPConnectionPool(host='ruidongcloud.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da5be1b90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
[spo-msedge.net] HTTPConnectionPool(host='spo-msedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1da6695d10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
